name= deploying ec2 instances:
on:
  push:
jobs:
  deploy:
    runs_on:ubuntu_latest
      steps:
        - run: deploy 500 gb harddisk:
        - run: deploy 24gb ram:
        - run: deploy hundred ec2 instances:
