name: deploying ec2 instances
on:
  push:
jobs:
  deploy:
    run-on: ubuntu-latest
      steps:
        - run: echo "deploy 500 gb harddisk"
        - run: echo "deploy 24gb ram"
        - run: echo "deploy hundred ec2 instances"
